In [ ]:
https://github.com/leblanc-gavin/leblanc-gavin.github.io.git

My name is Gavin LeBlanc and I will be conducting the final tutorial project by myself. Since i'm working by my lonesome, my only technologies used in this tutorial project will be GitHub, Jupiter Notebooks, Docker, Python, a few Python data parsing/scraping libraries such as Beautiful Soup, NumPy, pandas, requests and more to come throughout the development of the project.

Dataset 1: A century of trends in adult human height (https://elifesciences.org/articles/13410)
Possible Question: How average height amongst both men and women differ from region to region.

Dataset 2: CO2 emissions per capita Consumption based, tonnes per capita
(https://www.gapminder.org/data/)
Possible Question: Is there a direct correlation between population size and CO2 emissions?

Dataset 3: States Current and Historical Data for Covid-19 Tracking,
(https://api.covidtracking.com/v1/states/daily.csv)
Possible Question: Is there a direct correlation to population size of each state compared to the cases of covid-19 the same state saw?
Maybe there's a political factor considering the two political parties had different beliefs on the best way to combat covid-19, maybe one was more effective than the other at preventing unnecessary cases and deaths.

In [20]:
import pandas as pd
import requests
from io import StringIO
from IPython.display import display, Markdown

# URL of the Covid-19 CSV file
csv_url = "https://api.covidtracking.com/v1/states/daily.csv"  

# Step 1: Extract
response = requests.get(csv_url)

# Read the CSV with error handling
try:
    data = pd.read_csv(StringIO(response.text), on_bad_lines='warn') 
except Exception as e:
    print(f"An error occurred: {e}")

# Step 2: Transform
def transform_data(df):
    critical_columns = [
        "date", "state", "positive", "negative", 
        "totalTestResults", "hospitalizedCurrently", 
        "hospitalizedCumulative", "inIcuCurrently", 
        "onVentilatorCurrently", "recovered", "death"
    ]
    df = df[critical_columns].copy() 
    
    # Renaming for clarity
    rename_mapping = {
        "date": "Date",
        "state": "State",
        "positive": "Positive Cases",
        "negative": "Negative Cases",
        "totalTestResults": "Total Test Results",
        "hospitalizedCurrently": "Hospitalized Currently",
        "hospitalizedCumulative": "Hospitalized Cumulative",
        "inIcuCurrently": "ICU Currently",
        "onVentilatorCurrently": "On Ventilator Currently",
        "recovered": "Recovered",
        "death": "Deaths"
    }
    df.rename(columns=rename_mapping, inplace=True)

    return df




# Transform the data
transformed_data = transform_data(data)

# Step 3: Load (Display)
display(Markdown("# States Current and Historical Data for Covid-19 Tracking"))
display(transformed_data)

# States Current and Historical Data for Covid-19 Tracking

,Date,State,Positive Cases,Negative Cases,Total Test Results,Hospitalized Currently,Hospitalized Cumulative,ICU Currently,On Ventilator Currently,Recovered,Deaths
0,20210307,AK,56886.0,NaN,1731628.0,33.0,1293.0,NaN,2.0,NaN,305.0
1,20210307,AL,499819.0,1931711.0,2323788.0,494.0,45976.0,NaN,NaN,295690.0,10148.0
2,20210307,AR,324818.0,2480716.0,2736442.0,335.0,14926.0,141.0,65.0,315517.0,5319.0
3,20210307,AS,0.0,2140.0,2140.0,NaN,NaN,NaN,NaN,NaN,0.0
4,20210307,AZ,826454.0,3073010.0,7908105.0,963.0,57907.0,273.0,143.0,NaN,16328.0
...,...,...,...,...,...,...,...,...,...,...,...
20775,20200117,WA,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20776,20200116,WA,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20777,20200115,WA,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20778,20200114,WA,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20779,20200113,WA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

So to conclude the introduction of my project, along with some libraries I've used so far or eventually plan to use. I've presented three ideas for possible datasets to base this project on, including worldwide C02 emissions, worldwide height trends over the past century, and Covid-19 tracking data. The data i've chosen to use for an example of ETL in this project was the Covid-19 dataset which was located in a CSV file. My original final thought for a third project idea was data on the population 65 years and over in the united states but I ran into problems relating to the HTML and Javascript which ultimately just made me switch to the Covid-19 Tracking dataset to use for my example. The csv file that the data was located in was tremendously easier to parse, format, and display in the ETL process than the HTML body from my prior idea that kept throwing Javascript errors.